import Head from 'next/head'
import {test, connecting} from './api/hello'
import {useRouter} from 'next/router'
import { useEffect, useState } from 'react';



const Login = () => {

    let {id} = useRouter().query;
    const [info, Setinfo] = useState(test(id));
    
    useEffect(() => {
        async function name() {
            let x = await test(id)
            console.log(x);    
        }
        name();
    }, []);

return(
    <div>
        <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <a>test</a><br/>
            <a>{info}</a>
        </main>
    </div>
)
}

export default Login;